### PR TITLE
Implement simple weight input

### PR DESCRIPTION
**Pull request by NobodyForNothing**
implements #309

https://github.com/user-attachments/assets/a9db88e3-98f0-4c1f-8433-f9b79b8b8a81

### CODE REVIEW

**Comment by NobodyForNothing** [comment]
@xandro0777, I'm working on implementing your feature request for weight. If you could spare a minute: what do you think of the workflow seen in the video attached to this pr?

**Comment by NobodyForNothing** [comment]
I think the dialog (you are correct about the spelling, but dialoge isn't even german) is a bit faster to use than for a single new category.
I do admit that this is currently not a very clean implementation. I hoped to gain some more feedback before fully committing to this feature, so if you have more opinions or suggestion feel free. 

I can imagine a more sophisticated implementation that has a tab bar below the date picker, like on the home screen.

**Comment by xandro0777** [comment]
The Wright and a few other of the requested values would be typically a one per day, usually morning value so it would make sense to have it in a different tab. There is a wide variety of values and observations that people would want to record every morning or maybe evening so it would be nice to be able to add fields to this tab freely.

Some values like arrhythmia yes/no are pretty much tied to the blood pressure measurement and should fit into the main data entry form.

Other potential values like blood sugar or body temperature are sometimes once per day, sometimes more but frequently not at the same time as blood pressure.. yet another tab.

**Comment by NobodyForNothing** [comment]
@pimlie an implemented feature can't be taken away easily. So if weight input works on a smaller scale and stays maintainable I can manually add more categories. I won't let users define them, unless I get far more contributers, I already made that mistake with export columns. The way @xandro0777 described the relationship between values here makes sense to me. So there would be toggleable forms that would get composed into tabs and "superforms"(I lack a better word) in the add-entry-dialoge.

Thanks for the offer pim, more contributors are always great. (I'm a bit busy this weekend, so a proper review of your pr will take a bit)

**Pull request merged**
